var floatAge, floatDays, floatMonths, intWeeks, intFortnights;
    floatAge = parseFloat(prompt("Please enter your age in years."));
    floatDays = parseFloat(floatAge * 365.25).toFixed(2);
    floatMonths = parseFloat(floatAge * 12).toFixed(2);
    intWeeks = parseInt(floatDays / 7).toFixed(2);
    intFortnights = parseInt(floatDays /14).toFixed(2);
    alert("Your age in days is " + floatDays);
    alert("Your age in weeks is " + intWeeks);
    alert("Your age in fortnights is " + intFortnights);
    alert("Your age in months is " + floatMonths);